server:
  port: 8001
mybatis:
  type-aliases-package: com.liyiruo.springcloud.entities
  config-location: classpath:mybatis/cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}-hystrix
    prefer-ip-address: true




#datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: '!QAZ2wsx'
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
  application:
    name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据



management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
