server:
  port: 7001

spring:
  application:
    name: microservice-zuul-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,eureka6002.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

#zuul 是非常有用的。 请求为/product/** 的 将product 替换为  microservice-product
zuul:
  routes:
    provider-product:
      path: /product/**
      serviceId: microservice-product
      stripPrefix: false
