#端口号
server:
  port: 6001
#应用名称
#spring:
#  application:
#    name:
#Eureka相关配置
eureka:
  instance:
    hostname:  eureka-6001   #实例的名称
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/