#配置端口号
server:
  port: 8001
#配置mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/cfg.xml
  type-aliases-package: com.liyiruo.springcloud.entities

#datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: '!QAZ2wsx'
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
  application:
    name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据

#如果想把一个模块添加到注册中心，只需要添加eureka客户端依赖，注解 ，设置配置文件
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6002.com:6002/eureka, http://eureka6001.com:6001/eureka  #zone  这个Z 是大写的。
      #eureka 客户端配置实例名,页面上就不会在显示IP了
  instance:
    instance-id: ${spring.application.name}:${server.port}  # 指定实例ID,就不会显示主机名了
    prefer-ip-address: true #访问路径可以显示IP地址


